### ISSUE TITLE
Access to Hand Masks via Zenodo

### ISSUE THREAD

**Issue by ss8319** [aimi-bonn/Deeplasia#3]
The hand masks are available from [zenodo](https://doi.org/10.5281/zenodo.7415591).

Hi thank you for contributing to this project. Is it possible for me to gain access to the hand masks?

**Comment by sRassmann** [comment]
Thank you for your interest in out projects.
You are right, the link does not work any longer as we moved the zenodo archive to a new [link](https://zenodo.org/records/7415591). We should also update the link in the Readme of this project

**Comment by guinique** [comment]
hi, the link you posted is also blocked, how to obtain access?

**Comment by sRassmann** [comment]
This link should work now: https://zenodo.org/records/7611677

**Comment by guinique** [comment]
Thanks
