### ISSUE TITLE
Looking for guidance in running this code on my system

### ISSUE THREAD

**Issue by Chaudharysumit07** [aimi-bonn/Deeplasia#4]
Hello everyone, I am trying to run this code on my system  but the readme provided is not helping me much. I also tried to execute the docker service but it also required the deep learning model to be passed externally  to it and I am not able to understand how to do it. Can  you please guide me how to feed input, how to train models and predict on RSNA bone age dataset only. Any help will be very helpful. Thankyou in advance.

**Comment by sRassmann** [comment]
Hi, thanks for you interest in our project.
I assume with the docker you are referring to the [deeplasia-service](https://github.com/sRassmann/deeplasia-service) repo.
We are not providing the weights, however you can obtain yourself by training.
Roughly you'd need to download the RSNA dataset (images and csvs), merge and format the .csvs to contain the image names (from the dir with the input images), sex, and the bone_age, and generate a second .csv file indicating whether the image is `train`, `val`, or `test`.
