### ISSUE TITLE
Issue running the colab notebook

### ISSUE THREAD

**Issue by guinique** [aimi-bonn/Deeplasia#5]
Hi, I'm trying to run the colab notebook, but I have two main doubts:

1 - How should the data be structured inside the rsna_bone_age.zip that is mentioned in the code?

2 - Where would it be possible to obtain the DHA images and their respective annotations? Because when downloading from the link available in the readme using the google drive option, the dataset folder has images, but the ids of the images in the downloaded folder do not match the ids shown in the data/annotations.csv file.

Thanks in advance!

**Comment by sRassmann** [comment]
I assume you are referring to `nb/example_inference.ipynb`.

1 - I am not sure which zip you are referring to. You have to download the data, create a annotation scheme similar to `data/annotation.csv` with the respective columns (potentially renaming the images), and move the data to the right location (I think "../data/annotated/" by default).

2 - You have to obtain it from the website of the [USC](https://ipilab.usc.edu/research/baaweb/) or from kaggle. You can likely resolve the annotation via the patient_ID in the example annotation file as they were taken from the image names as downloaded.

**Comment by sRassmann** [comment]
You can also check this repo: https://github.com/razorx89/digital-hand-atlas-downloader

**Comment by guinique** [comment]
The notebook i was refering to is nb/Colab_script.ipynb, now i understood that the annotations.csv is an example, the only problem now is that i can't acces the DHA dataset, i already tried this repo: https://github.com/razorx89/digital-hand-atlas-downloader but it didn't returned any images.

Thanks for your reply, if i cant find a way to use DHA i'll just train with RSNA.

**Comment by sRassmann** [comment]
The Google Drive download should still work: https://drive.google.com/file/d/1dVkT4EgxTtgJtUDh28bkHR_aWd8tESO5/view?pli=1
